name: Test building debian package

on: pull_request

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  debian-package:
    name: "Build debian package"
    runs-on: ubuntu-latest
    container:
      image: "debian:12"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install devscripts dpkg-dev debhelper equivs curl gnupg
          echo "deb https://packagecloud.io/faucetsdn/faucet/$(lsb_release -si | awk '{print tolower($0)}')/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/faucet.list
          curl -1sLf https://packagecloud.io/faucetsdn/faucet/gpgkey -o /etc/apt/trusted.gpg.d/faucet.asc
          echo "deb https://packagecloud.io/faucetsdn/faucet-test/$(lsb_release -si | awk '{print tolower($0)}')/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/faucet-test.list
          curl -1sLf https://packagecloud.io/faucetsdn/faucet-test/gpgkey -o /etc/apt/trusted.gpg.d/faucet-test.asc
          apt-get update
      - name: Bump version
        run: |
          export DEBEMAIL='maintainers@faucet.nz'
          export DEBFULLNAME='Faucet Maintainers'
          debchange -b "Test release"
      - name: Build package
        run: |
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
          dpkg-buildpackage -b -us -uc -rfakeroot
